main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/user_login/', views.user_login, name='user_login'),    
        
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('accounts/<int:user_profile_id>/add_user_photo/', views.add_user_photo, name='add_user_photo'),    
    
    path('projects/', views.projects_index, name='index'),
    path('projects/create/', views.ProjectCreate.as_view(), name='projects_create'),
    path('projects/<int:project_id>/', views.projects_detail, name='detail'),
    
    path('projects/<int:project_id>/update/',views.projects_update, name='projects_update'),
    
    path('projects/<int:pk>/delete/', views.ProjectDelete.as_view(), name='projects_delete'),
    path('projects/<int:project_id>/add_task/', views.add_task, name='add_task'),
    path('update_task/<int:task_id>/', views.update_task, name='update_task'),
    path('projects/<int:project_id>/add_project_note/', views.add_project_note, name='add_project_note'),
    path('projects/<int:project_id>/assoc_member/<int:team_member_id>/',views.assoc_member, name='assoc_member'),
    path('projects/<int:project_id>/unassoc_member/<int:team_member_id>/',views.unassoc_member, name='unassoc_member'),
    path('projects/<int:project_id>/add_photo/',views.add_photo, name='add_photo'),
]

projecthub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
# AbstractUser
from django.core import validators

# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    start_date = models.DateField()
    end_date = models.DateField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    team_members = models.ManyToManyField(User, through='TeamMember', related_name='projects')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'project_id': self.id})
    
    def save(self, *args, **kwargs):
        if not self.pk:
            super(Project, self).save(*args, **kwargs)
            TeamMember.objects.create(project=self, user=self.created_by)
        else:
            super().save(*args, **kwargs)

class ProjectNote(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    note = models.TextField(max_length=150)

    def __str__(self):
        return f"{self.note} is a note for {self.project}"

# Define after project.
# we essentailly want team member to serve as an intermediary between users
# and projects. we needed a second way to access it.
# by using 'through' up above we are effictively able to use users twice
class TeamMember(models.Model):
    #use related_name=to avoid the errors
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_member')
    project= models.ForeignKey(Project, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.user.username
    
class Task(models.Model): 
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    due_date = models.DateField()
    status = models.BooleanField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    assigned_to = models.ForeignKey(TeamMember, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return f"{self.name} is a task for {self.project} due on {self.due_date}"

    def save(self, *args, **kwargs):
        if not self.project_id:
            self.project_id = project_id
        super (Task, self).save(*args, **kwargs)

    @property
    def status_display(self):
        return "Complete" if self.status else "Incomplete"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for project_id: {self.project_id} @{self.url}"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    bio = models.TextField(max_length=200)
    
    first_name = models.CharField(('first name'), max_length=150, blank=True)
    last_name = models.CharField(('last name'), max_length=150, blank=True)
    email = models.EmailField(('email address'), blank=True)
    
    def __str__(self):
        return self.user.username

class ProfilePhoto(models.Model):
    url = models.CharField(max_length=200)
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    key = models.CharField(max_length=200, default='')

    def __str__(self):
        return f"Photo for user_id: {self.user_profile_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task, Project, UserProfile, ProjectNote

class TaskForm(ModelForm):
    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        input_formats=['%m-%d-%Y', '%m/%d/%Y', '%Y-%m-%d'],
        required=False       
    )
    class Meta:
        model = Task
        fields = ['name', 'description', 'due_date', 'status', 'assigned_to']
        widgets = {'project': forms.HiddenInput()} 

class ProjectForm(forms.ModelForm):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        input_formats=['%m-%d-%Y', '%m/%d/%Y', '%Y-%m-%d'],
        required=False
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        input_formats=['%m-%d-%Y', '%m/%d/%Y', '%Y-%m-%d'],
        required=False       
    )
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date']

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date']

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'bio', 'email']

class ProjectNoteForm(forms.ModelForm):
    class Meta:
        model = ProjectNote
        fields = ['note']

main_app/views.py
import uuid
import boto3
import os

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TaskForm, ProjectForm, UserProfileForm, ProjectNoteForm, ProjectUpdateForm
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .models import Project, TeamMember, Photo, Task, UserProfile, ProfilePhoto, ProjectNote
from django.utils.dateparse import parse_date

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def projects_index(request):
  projects = Project.objects.filter(team_members=request.user)
  return render(request, 'projects/index.html', {
    'projects': projects
  })

class ProjectCreate(LoginRequiredMixin, CreateView):
  model = Project
  form_class = ProjectForm
  template_name = 'main_app/project_form.html'

  def form_valid(self, form):
    form.instance.created_by = self.request.user
    return super().form_valid(form)

class ProjectDelete(LoginRequiredMixin, DeleteView):
  model = Project
  success_url = '/projects'

@login_required
def projects_update(request, project_id):
    project = Project.objects.get(id=project_id)
    
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('detail', project_id=project_id)
    else:
        form = ProjectForm(instance=project)

    return render(request, 'projects/update_project.html', {'form': form})
    
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
        error_message = 'Invalid sign up - try again!'
  form = UserCreationForm()
  context = {'form' : form, 'error_message' : error_message}
  return render (request, 'registration/signup.html', context)

@login_required
def projects_detail(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == 'POST':
      project_update_form = ProjectUpdateForm(request.POST, instance=project)
      if project_update_form.is_valid():
        project_update_form.save()
        return redirect('detail', project_id=project_id)

    else:
        project_update_form = ProjectForm(instance=project)
    #grabbed users here
    all_users = User.objects.all()
    # check team members here
    team_members_id = project.team_members.all()
    # filter team members from all users
    members_not_in_team = all_users.exclude(id__in=team_members_id)
    task_form = TaskForm()
    project_note_form = ProjectNoteForm()
    tasks= Task.objects.filter(project_id=project_id)
    project_notes = ProjectNote.objects.filter(project_id=project_id)
    return render(request, 'projects/detail.html', {
        'project': project,
        'task_form': task_form,
        'project_note_form' : project_note_form,
        'members_not_in_team': members_not_in_team,
        'tasks' : tasks,
        'project_notes' : project_notes,
        'project_update_form' : project_update_form
    })

@login_required
def add_task(request, project_id):
  project= Project.objects.get(pk=project_id)
  if request.method == 'POST':
    form = TaskForm(request.POST)
    if form.is_valid():
      new_task = form.save(commit=False)
      new_task.project_id = project_id
      new_task.project=project
      new_task.save()
    return redirect('detail', project_id=project_id)
  else:
    form = TaskForm()
  tasks = Task.objects.filter(project=project)

  context = {
    'project' : project,
    'tasks' : tasks,
    'task_form' : form,
  }
  return render(request, 'detail.html', context)

@login_required
def update_task(request, task_id):
  if request.method == 'POST':
    task = Task.objects.get(pk=task_id)
    new_status = request.POST.get('status', False) == 'on' 
    task.status = new_status
    task.save()

  return redirect('detail', project_id=task.project_id)

@login_required
def add_project_note(request, project_id):
  form = ProjectNoteForm(request.POST)
  print(f"before form is valid: {form}")
  if form.is_valid():
    new_note = form.save(commit=False)
    new_note.project_id = project_id
    new_note.save()
  return redirect('detail', project_id=project_id)

@login_required
def assoc_member(request, project_id, team_member_id):
  Project.objects.get(id=project_id).team_members.add(team_member_id)
  return redirect('detail', project_id=project_id)

@login_required
def unassoc_member(request, project_id, team_member_id):
  Project.objects.get(id=project_id).team_members.remove(team_member_id)
  return redirect('detail', project_id=project_id)

@login_required
def add_photo(request, project_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        # It needs to keep the same file extension of
        # the file that was uploaded (.png, .jpeg, etc..)
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, project_id=project_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', project_id=project_id)

def user_login(request):
    error_message = ''
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')  
            else:
                error_message = 'Invalid login - try again'
    else:
        form = AuthenticationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'user_login.html', context)


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'user_profile.html'

    def get(self, request):
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        form = UserProfileForm(instance=user_profile)
        print(f" get for user_profile,(id): {user_profile}, ({user_profile.id}), req.user.id: {request.user.id}")
        return render(request, self.template_name, {'form': form, 'user_profile': user_profile})

    def post(self, request):
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            print(f"form post is valid for user_profile: {user_profile}")
            form.save()
            print(f"form post SAVED for user_profile: {user_profile}")
            return redirect('user_profile')
        return render(request, self.template_name, {'form': form, 'user_profile': user_profile})


@login_required
def add_user_photo(request, user_profile_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    print(f"I have reached the add_user_photo URL")
    if photo_file:
        s3 = boto3.client('s3')        
        key = uuid.uuid4().hex[:6] + photo_file.name[:photo_file.name.rfind('.')]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign profilephoto to req.user.userprofile
            # since that's the object w One:One relationship           
            profilephoto = request.user.userprofile.profilephoto
            if profilephoto:
              if profilephoto.key:
                s3.delete_object(Bucket=bucket, Key=profilephoto.key)
                print(f"the old user_profilephoto was deleted") 
              # Now update the key, url for profilephoto and save to db             
              profilephoto.key = key
              profilephoto.url = url
              profilephoto.save()
            else:
              ProfilePhoto.objects.create(url=url, user_profile_id=user_profile_id, key=key)
              print('We made it to try part')
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('user_profile')

main_app/templates/projects/detail.html
{% extends 'base.html' %}
{% block content %}

{% comment %} sidebar {% endcomment %}
<div class="row">
  <div class="sidebar-container">
    <div class="col-md-3">
      <nav id="navbar-side" class="navbar navbar-light bg-light flex-column align-items-stretch p-3 shadow-lg">
        <div class="navbar-brand"> Tools </div>
        <nav class="nav nav-pills flex-column">
          <a class="btn btn-primary mb-2 " href="{% url 'projects_delete' project.id %}">Delete </a>
          <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
          data-bs-target="#updateModal">
            Update
          </button>
          <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
          data-bs-target="#memberModal">
            View or remove members
          </button>
          <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
          data-bs-target="#nonMemberModal">
            Add Members
          </button>
          <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
          data-bs-target="#addTaskModal">
            Add Task
          </button>
          <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
          data-bs-target="#addPhotoModal">
            Add Photo
          </button>
        </nav>
      </nav>
    </div>
  </div>
  {% comment %} end sidebar {% endcomment %}
  <div class="container">      
    <div class="modal fade" id="memberModal" tabindex="-1" aria-labelledby="memberModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="memberModalLabel">TEAM MEMBERS</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% if project.team_members.all %}
            <div>
              <ul>
                {% for member in project.team_members.all %}
                <li>
                  {{ member.username }}
                  <form action="{% url 'unassoc_member' project.id member.id %}" method='POST'>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Remove</button>
                  </form>
                </li>
                {% endfor %}
              </ul>
            </div>
            {% else %}
            <p>No team members assigned to this project.</p>
            {% endif %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="memberModalLabel">Update Project</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form class="" action="{% url 'detail' project_id=project.id %}" method="POST">
              {% csrf_token %}
              {{ project_update_form.as_p }}
              <button type="submit" class="btn btn-primary">Update Project</button>
          </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="nonMemberModal" tabindex="-1" aria-labelledby="nonMemberModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="nonMemberModalLabel">ADD MEMBERS</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% if members_not_in_team %}
            <div>
              <ul>
                {% for team_member in members_not_in_team %}
                <li>
                  {{ team_member.username }}
                  <form action="{% url 'assoc_member' project.id team_member.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Add</button>
                  </form>
                </li>
                {% endfor %}
              </ul>
            </div>
            {% else %}
            <p>No available team members to add to this project.</p>
            {% endif %}        
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="AddTaskModalLabel">Add Task</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div id="taskForm">
              <form action="{% url 'add_task' project.id %}" method="POST">
                {% csrf_token %}
                <p>Name: </p> {{task_form.name}}
                <br>
                <p> Description: </p> {{task_form.description}}
                <br>
                <p> Due Date: </p> {{task_form.due_date}}
                <br>
                <p> Assigned To: </p> {{task_form.assigned_to}}
              </div>
            </div>
            <div class="modal-footer">
              <input type="submit" class="btn btn-primary" value="submit">
            </form>
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Photo Section BEGINS here -->
    <div class="modal fade" id="addPhotoModal" tabindex="-1" aria-labelledby="addPhotoModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="addPhotoModalLabel">Project Photos</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div>
              <form action="{% url 'add_photo' project.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
                {% csrf_token %}
                <input type="file" name="photo-file">
                <br><br>
                <button type="submit" class="btn btn-primary">Upload Photo</button>
              </form>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Photo section ENDS  -->

    <div class="container">      
      <div class="modal fade" id="noteModal" tabindex="-1" aria-labelledby="noteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="noteModalLabel">Add a Note</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="form-outline mb-4">
                <form action="{% url 'add_project_note' project.id %}" method="POST">
                  {% csrf_token %}
                  {{project_note_form.note}}
                </div>
              </div>
              <div class="modal-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    <div class="col-md-9">
      <div class="card-center">
        <div class="card shadow-lg mt-3" style="width: 36rem;" id="proj-card">
          <div class="card-body">
            <h5 class="card-title" id="project-name">{{ project.name }}</h5>
            <hr class="hr hr-blurry" />
            <h6 class="card-subtitle mb-2 text-muted"><span id="manage-call">Project Manager: {{ project.created_by }} </span></h6>
            <div class="card-footer">
              Start: {{ project.start_date }} <br> End: {{ project.end_date }}
            </div>
            <hr class="hr hr-blurry" />
            <p class="card-text">{{ project.description }}</p>
            <hr class="hr hr-blurry" />
            <!--tasks starts-->
            <div id="tasks">
              <h5 class="card-title">Tasks</h5>
      {% if tasks %}
      <ul>
        {% for task in tasks %}
        <li>{{ task.name }} </li>
          <ul>
            <li> Assigned to- {{task.assigned_to}}</li>
              <ul>
                <form id="form-{{ task.id }}" action="{% url 'update_task' task.id %}" method="POST"> 
                {% csrf_token %}
                <li>
                  <input type="checkbox" name="status" {% if task.status %}checked{% endif %} onchange="updateTask({{ task.id }})">
                  {{task.status_display}}
                </form>
                </li>
              <li> {{ task.description }} </li>
              <li> Due Date: {{ task.due_date }}</li>
              </ul>
          </ul>
        {% endfor %}
      </ul>
      {% else %}
      <p>No tasks for this project.</p>
      {% endif %}
    </div>
    <!--end tasks-->
    <!-- photo carousel -->
    {% if project.photo_set.all %}
    <hr class="hr hr-blurry" />
      <div id="photoCarousel" class="carousel slide">
        <div class="carousel-inner">
          {% for photo in project.photo_set.all %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img src="{{ photo.url }}" class="d-block w-100" alt="project picture">
          </div>
          {% endfor %}
        </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#photoCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#photoCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
      </button>
      </div>
      <!--end carousel -->
      <hr class="hr hr-blurry">
      {% else %}
      <hr class="hr hr-blurry">
      {% endif %}
      <div id="notes">


        <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-lg-6">
          <div class="card shadow-0 border">
            <div class="card-body p-4" style="background-color: rgb(175, 175, 175);">
              <div class="card mb-4">
                <div class="card-body">
                  {% if project_notes %}
                  {% for note in project_notes %}
                  <p>-{{ note.note }}</p>
                  <hr class="hr">
                  {% endfor %}
                  {% else %}
                  <p> no notes to display</p>
                  {% endif %}
                  <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal"
                  data-bs-target="#noteModal">
                    Add a Note
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      </div>
      <!--end notes-->


    </div>
  </div>
</div>
    </div>
    <!--end card-->
  </div>
  <!--end col 9-->
  

</div>


<script>
  function updateTask(taskId) {
    const formElement = document.getElementById(`form-${taskId}`);
    formElement.submit();
  }
  </script>
{% endblock %}

main_app/templates/projects/index.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-9">
  <div class="card-center">
    <div class="card shadow-lg mt-3" style="width: 36rem;" id="proj-card">
      <div class="card-body">
        <h6 class="card-title" id="project-name">Project List</h5>
          {%if projects.count%}
          {% for project in projects %}
          <hr class= "hr hr-blurry">
        <h5 class="card-title"><a href= {% url 'detail' project.id %}>{{project.name}}</a></h5>
        <h6 class="card-subtitle mb-2 text-muted">{{project.created_by}}</h6>
        {% endfor %}
        {%else%}
        <p>
          <hr class="hr hr-blurry">
          Looks like you have no projects! 
          <br>
            <a class="btn btn-primary mt-3"  href="{% url 'projects_create' %}"> Create a new project</a>
        </p>
    {%endif%}
      </div>
    </div>
  </div>
</div>

{% endblock %}